name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd Fuel-Comparison
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          pkill uvicorn || true
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > output.log 2>&1 &
